# Generated by Django 5.2 on 2025-05-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addres_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addres_line_2',
            new_name='address_line_2',
        ),
    ]
